<a href="https://colab.research.google.com/github/jiyakaushik26/Data-science/blob/main/Day_4(NumPy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


# **NUMPY LIBRARY :**
for faster operations through

Function to create an array
1. a= numpy.array ()

=> pass list , set as argument

=> numpy arrays are also called vectors

In [ ]:
myarr=np.array([2,3,4,5])
print(myarr)

[2 3 4 5]


In [ ]:
myarr=np.array([2,3,4,5], np.int32)
print(myarr)

[2 3 4 5]


When you create a NumPy array, all elements must have the same **data type (dtype).**

Since a string cannot be safely converted to an integer automatically, NumPy chooses a data type that can hold all values.

 A string can represent both numbers and text, so **NumPy upcasts everything to strings.**

In [ ]:
a = np.array ([1,2,3,'4'])
print(a) # converts all the elements to string

print(a.dtype)

['1' '2' '3' '4']
<U21


**U** = Unicode string

**21** = maximum length allocated for each string element

Since the array contains a string ('hello'), NumPy converts all elements to **strings**

bool('False') gives true as now false is a string not a boolean value,
it retruns true because any non-empty string is True and if it had been->



1.  bool(' ') -> True

2. bool('') -> False


bool(0)-> False

bool(5)->True

bool('')->False

bool('abc')-> True

bool(False)->False

bool(True)->True



In [ ]:
np_arr=np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1])) #wherever there is value, boolean conversion will result into true.

True


**Numpy.zeroes()**->

creates an array filled with zeroes

**Format**->

a = np.zeros(shape, dtype=datatype)

shape passed as list or tuple

**By default, np.zeros() creates floating-point numbers**

In [ ]:

a = np.zeros((2, 3), dtype=int)
print(a)

b= np.zeros(4)
print(b)

c=np.zeros((2,3,4))
print(c)
print(type(c[0][0][0])) #<class 'numpy.float64'>

d=np.zeros((2,3,4),dtype=int)
print(type(d[0][0][0])) #<class 'numpy.int64'>

[[0 0 0]
 [0 0 0]]
[0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>
<class 'numpy.int64'>


**numpy.empty()**-> Creates an array without initializing values.

**Format**-> a = np.empty(shape, dtype=datatype)


In [ ]:
a = np.empty(5, dtype=int)
print(a)

[                  0 4598175219545276416 4602678819172646912
 4604930618986332160 4607182418800017408]


**numpy.full()**-> Creates an array filled with a specified value.

**Format->** a = np.full(shape, fill_value, dtype=datatype)

In [ ]:
a=np.full(4,5)
print(a)

b=np.full((3,4),7)
print(b)

[5 5 5 5]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


**numpy.arange**-->is a built-in NumPy function that creates a one-dimensional array of evenly spaced numeric values within a defined interval

**Format->** **numpy.arange(start, stop, step, dtype=int)**

**stop** is exclusive.


In [ ]:
b = np.arange(3, 12, 4, dtype=int)
print(b)

[ 3  7 11]


Since only one argument is given, NumPy treats it as the stop value and by default step is 1 and start value is 0

Think of np.arange() exactly like Python's range(), but it returns a NumPy array instead of a range object.

In [ ]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


**numpy.linspace()**--> It creates num equally spaced values between start and stop.

**Format->** np.linspace(start, stop, num)

**with endpoint=False->**  Now stop is not included.

**Effect of dtype=int->** So NumPy converts those float values to integers:

In [ ]:
b=np.linspace(5, 10, 3)
print(b)

c = np.linspace(5,10,3,dtype=int, endpoint = False) # start, stop, number of values
# here endpoint is included, need to manually turn it to false
print(c)

[ 5.   7.5 10. ]
[5 6 8]


**np.ones->** Creates an array filled with 1s.


In [ ]:
a = np.ones((2,3),dtype=int)
print(a)

print(np.shape(a)) # tells abput the dimension

print(np.size(a)) # total number of elements

[[1 1 1]
 [1 1 1]]
(2, 3)
6


**np.random.randint(low, high, size)** ->

low → smallest possible value (included)

high → largest value is not included

size → generate n random numbers

[low, high)

In [ ]:
a=np.random.randint(8,10,5)
print(a)

b=np.random.randint(1, 6, 10)
print(b)

[8 9 8 8 8]
[5 5 2 5 4 4 5 2 5 5]


**Creating a 2D random array**

In [ ]:
a = np.random.randint(1, 10, (2, 3))
print(a)

[[9 7 2]
 [7 8 1]]


**np.random.choice(array_or_list, size)** ->randomly selects elements from the given list.

by default, repetition is allowed.

 **replace=False**-> because duplicates are not allowed.

In [ ]:
a = np.random.choice([2,3,5,8], 2, replace=False)
print(a)

[5 2]


In [ ]:
a = np.random.choice([2,3,5,8])
print(a)

5


# Broadcasting

It is NumPy's way of making arrays with different shapes work together in arithmetic operations.

In [ ]:
a = np.array([1, 2, 3])

print(a + 5)

[6 7 8]


In [ ]:
a = np.ones((3,3), dtype=int)

b = np.array([1,2,3])

print(a + b)

[[2 3 4]
 [2 3 4]
 [2 3 4]]


For broadcasting, dimensions must be:

Equal, OR

One of them must be 1

In [ ]:
a = np.ones((3,3), dtype = int)
b = np.ones((3,3), dtype = int)
print (a)

print(a*2)

print(a+b)

print(a-b)

print(a*b)

print(a//b)
# elements at corresponding positionn are being operated.

c=np.ones((2,2), dtype=int)
# print(a+c) -> ValueError : operands could not be broadcast together with different shapes

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
a = [2,3,4]
print(a*2) # prints the list twice 💁🏻‍♀️

[2, 3, 4, 2, 3, 4]


reshape((3,2))-> You are asking NumPy to rearrange the same 6 elements into:


3 rows
2 columns

In [ ]:
a = np.random.randint(2,15,6)
print(a)
b = a.reshape((3,2))
print(b)

[ 4 13  4 13 12  2]
[[ 4 13]
 [ 4 13]
 [12  2]]


In [ ]:
a = np.random.randint(2,16,8)
b = a.reshape((2,4))
print(b)

c=b.transpose()
print(c)



[[ 6 13  6  7]
 [10 11  9 10]]
[[ 6 10]
 [13 11]
 [ 6  9]
 [ 7 10]]


**Concatenate->**

axis=0 → rows (vertical)

axis=1 → columns (horizontal)

In [ ]:
a = np.random.randint(2,16,8)
e = a.reshape((2,4))
print(e)

d = np.concatenate((b,e),axis=1) #
print(d)

f=np.concatenate((b,e), axis=0)
print(f)

[[11 11 15  2]
 [15  4 12  2]]
[[ 6 13  6  7 11 11 15  2]
 [10 11  9 10 15  4 12  2]]
[[ 6 13  6  7]
 [10 11  9 10]
 [11 11 15  2]
 [15  4 12  2]]


**np.where(condition, value_if_true, value_if_false)** -->

It checks the condition for each position and chooses:

value_if_true if condition is True

value_if_false if condition is False

In c, it takes it element when b>2 from b  and if at that index, b is not greater than 2 or condition is false, takes the elemnt from a

In [ ]:
a = np.random.randint(2,16,8)
print(a)
b = np.random.randint(2,16,8)
print(b)

c = np.where(b > 2, b, a)
print(c)

[14  5 13  6 10 10 14 13]
[15  9  7  6  2  6  2  6]
[15  9  7  6 10  6 14  6]


Sort

In [ ]:
a = np.random.randint(2,16,8)
print(a)
b = np.sort(a)
print(b)

[ 9  7 12  2  5 14  6 12]
[ 2  5  6  7  9 12 12 14]


Sum

In [ ]:
a = np.random.randint(2,16,8)
print(a)
b = np.sum(a)
print(b)

[10 12 14 15  6 11 15 10]
93


Mean value

In [ ]:
a = np.random.randint(2,16,8)
print(a)
b = np.mean(a)
print(b)

[10  8  9 15 10 10 14 12]
11.0


Standard deviation

In [ ]:
a = np.random.randint(2,16,8)
print(a)
b = np.std(a) # standard deviation
print(b)

[13 10  9 12 14  2  7  9]
3.570714214271425


Minimum value

In [ ]:
a = np.random.randint(2,16,8)
print(a)
b = np.min(a)
print(b)

[11 10  7  4 10 11  4  5]
4


Maximum value

In [ ]:
a = np.random.randint(2,16,8)
print(a)
b = np.max(a)
print(b)

[ 6  5  2 14 13 13  4  3]
14


**np.unique() **returns only the distinct (unique) values basically removes the duplicate values from an array and automatically sorts them.

In [ ]:
a = np.random.randint(2,16,8)
print(a)
b = np.unique(a)
print(b)

[ 4  9 13  9  9  4  3 14]
[ 3  4  9 13 14]


**matrix multiplication** using np.matmul().

In [ ]:
a = np.random.randint(2,16,8)
a = a.reshape((2,4))
print(a)

b = np.random.randint(2,16,8)
b = b.reshape((4,2))
print(b)

c = np.matmul(a,b)
print(c)

[[12  4 14 10]
 [ 3  2  6 12]]
[[15 12]
 [ 6 13]
 [13  3]
 [ 7  3]]
[[456 268]
 [219 116]]


The **split()** method in Python breaks a single string into a list of smaller substrings based on a specified delimiter

**map(function, iterable)** applies the function to every element.

**map()** does not directly return a list. It returns a map object. so write list to convert it into a list

**np.argmax(scores)** -> Returns the index of the maximum value.

**np.argmin(scores)** -> Returns the index of the minimum value.

In [ ]:
scores = input()
# scores = np.random.randint(0,100,7)
scores = scores.split()
# scores =[int(x) for x in scores] -> another way to convert in integer
scores = list(map(int,scores))
days = ["MON","TUES","WED","THURS","FRI","SAT","SUN"]
scores = np.array(scores)
for i in range (len(scores)):
  print(scores[i],days[i])
print("maximum score : ", np.max(scores), "on ", days[np.argmax(scores)])
print("minimum score : ", np.min(scores), "on ", days[np.argmin(scores)])
print("sum of scores : ", np.sum(scores))
print("mean of scores : ", np.mean(scores))
print("standard deviation of scores", np.std(scores))

45
45 MON
maximum score :  45 on  MON
minimum score :  45 on  MON
sum of scores :  45
mean of scores :  45.0
standard deviation of scores 0.0


In [ ]:
scores = []
days = ["MON","TUES","WED","THURS","FRI","SAT","SUN"]

for i in range (7):
  x=input(f'give the input for the {days[i]}: ') #fstring : variables inside a string

give the input for the MON: 34
give the input for the TUES: 234
give the input for the WED: 231
give the input for the THURS: 13
give the input for the FRI: 11
give the input for the SAT: 23
give the input for the SUN: 33


(f'-----')--> is used as backticks are used in js

**b=a** ->This does not create a new array.

Both a and b point to the same NumPy array in memory.

In [ ]:
#Question 1
a = np.array([3,3,3,3])
b = a
b[0] = 1
a[-1]=6
print(a,b)

[1 3 3 6] [1 3 3 6]


In [4]:
n=int(input())
items=[]
prices=[]
for i in range(1,n+1):
  x=input(f'enter item number {i}:')
  y=int(input(f'enter the price for item {x} :'))
  items.append(x)
  prices.append(y)
prices = np.array(prices)
for i in range (len(prices)):
  print(items[i]," ",prices[i])
print("maximum price : ", np.max(prices), "of ", items[np.argmax(prices)])
print("minimum price : ", np.min(prices), "of ", items[np.argmin(prices)])
print("sum of all the prices : ", np.sum(prices))
print("mean of all the prices : ", np.mean(prices))
print("standard deviation of prices : ", np.std(prices))

3
enter item number 1:mago
enter the price for item mago :29
enter item number 2:apple
enter the price for item apple :30
enter item number 3:nike shoes
enter the price for item nike shoes :600
mago   29
apple   30
nike shoes   600
maximum price :  600 of  nike shoes
minimum price :  29 of  mago
sum of all the prices :  659
mean of all the prices :  219.66666666666666
standard deviation of prices :  268.9365889738488


**Axis** can be used for any operation but the suntax would be

**np.func(a, axis=0)** where func can be sum,min,max,etc



**To count->** np.count_nonzero(condition, axis)

or

**To count->** np.sum(np.where(condition, 1, 0))

In [22]:
a=np.random.randint(1,90, (5,5))
print(a)
b=np.mean(a,axis=1)
print(b)
c=np.mean(a,axis=0)
print(c)
d=np.where(a%2==0, -1, a)
print(d)
e=np.sort(a, axis=0)
print(e)
f=np.sort(a,axis=0)
print(f)
g=np.sum(a,axis=0)
print(g)
h=np.sum(a,axis=1)
print(h)
i = np.count_nonzero(a<0, axis=0)
print(i)

j=np.sum(np.where (a<0, 1, 0))
print(j)

[[37 73 80 21 53]
 [16 11 78 21 53]
 [33  3 17 68 68]
 [76 38 22 25 75]
 [ 3  7  7 61 69]]
[52.8 35.8 37.8 47.2 29.4]
[33.  26.4 40.8 39.2 63.6]
[[37 73 -1 21 53]
 [-1 11 -1 21 53]
 [33  3 17 -1 -1]
 [-1 -1 -1 25 75]
 [ 3  7  7 61 69]]
[[ 3  3  7 21 53]
 [16  7 17 21 53]
 [33 11 22 25 68]
 [37 38 78 61 69]
 [76 73 80 68 75]]
[[ 3  3  7 21 53]
 [16  7 17 21 53]
 [33 11 22 25 68]
 [37 38 78 61 69]
 [76 73 80 68 75]]
[165 132 204 196 318]
[264 179 189 236 147]
[0 0 0 0 0]
0


In [38]:
stock=np.random.randint(20,81,(5,5))
print(stock)
demand=np.random.randint(20,81,(5,5))
print(demand)
a= stock-demand
print(a)
b=abs(np.sum(np.where(a<0,a,0), axis=1))
print(b)
d=np.where(a<0, 0 ,a)
print(d)
c=np.count_nonzero(d==0, axis=1)
print(c)

e=np.sort(d, axis=0)
print(e)

[[30 61 35 72 52]
 [64 65 29 76 51]
 [30 33 53 69 80]
 [71 62 40 52 26]
 [63 71 28 35 24]]
[[24 69 63 49 58]
 [38 41 38 65 36]
 [40 80 24 61 37]
 [36 49 62 28 76]
 [61 77 60 74 68]]
[[  6  -8 -28  23  -6]
 [ 26  24  -9  11  15]
 [-10 -47  29   8  43]
 [ 35  13 -22  24 -50]
 [  2  -6 -32 -39 -44]]
[ 42   9  57  72 121]
[[ 6  0  0 23  0]
 [26 24  0 11 15]
 [ 0  0 29  8 43]
 [35 13  0 24  0]
 [ 2  0  0  0  0]]
[3 1 2 2 4]
[[ 0  0  0  0  0]
 [ 2  0  0  8  0]
 [ 6  0  0 11  0]
 [26 13  0 23 15]
 [35 24 29 24 43]]
